### ISSUE TITLE
Improve error messages with views/contexts

### ISSUE THREAD

**Issue by matthewtraughber** [darcy-framework/darcy-webdriver#67]
With the current system, it's particularly difficult to determine which required elements in a view / page object are not found, throwing errors. See the below example error:

```
com.synq.TimeoutException: Timed out after PT1M waiting for event to occur.
Event occurs when action is finished (com.autotest.pages.LoginPage$$Lambda$61/224219987@242b6e1a)
and then the item under examination is a View that is loaded in context, com.darcy.webdriver.WebDriverBrowser@333c8791,
  however the last examined result was, "com.autotest.pages.HomePage@671d1157",
  which is not a View that is loaded in context, com.darcy.webdriver.WebDriverBrowser@333c8791 (as determined by polling every PT1S)
```

What's unclear in the error message above, is there is a problem with the view for com.autotest.pages.HomePage (potentially ```@Required``` elements that are not being found).

**Comment by alechenninger** [comment]
Thanks for the feedback! This is something of a known issue, many people are unhappy with this (including myself). Let's continue the discussion here: https://github.com/darcy-framework/darcy-ui/issues/55 (you can also see some back story)
