### ISSUE TITLE
Add Selenium 3 support

### ISSUE THREAD

**Issue by jvervaec** [darcy-framework/darcy-webdriver#72]
Selenium 3 has been out for awhile now.  It appears to have lots of useful new features.  Selenium 2 also seems to have stopped supporting Firefox versions greater than 47.

Feel free to assign this one to me.  Will open a PR shortly.

**Comment by alechenninger** [comment]
Awesome, thanks!

**Comment by alechenninger** [comment]
Fixed in #73
